[design_space]
    f_s_min_max_list=[50e3, 300e3]
    l_s_min_max_list=[20e-6, 900e-6]
    l_1_min_max_list=[10e-6, 10e-3]
    l_2__min_max_list=[10e-6, 1e-3]
    n_min_max_list=[3, 7]
    transistor_1_name_list=['CREE_C3M0065100J', 'CREE_C3M0120100J']
    transistor_2_name_list=['CREE_C3M0060065J', 'CREE_C3M0120065J']
    c_par_1=16e-12
    c_par_2=16e-12

[filter_distance]
    number_filtered_designs = 2
    difference_percentage = 5

[thermal_data]
    # [tim_thickness, tim_conductivity]
    transistor_b1_cooling = [1e-3,12.0]
    transistor_b2_cooling = [1e-3,12.0]
